# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(47)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
# Import pandas 
import pandas as pd
import numpy as np

In [0]:
from sklearn.datasets import load_iris
iris_data = load_iris()

In [6]:
iris_data

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X = iris_data.data   #independent columns
Y = iris_data.target #target column

In [8]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X, Y, test_size=0.25, random_state=7)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
from sklearn.preprocessing import OneHotEncoder
OHE = OneHotEncoder(categories='auto')
Y1_train = OHE.fit_transform(Y_train.reshape(-1,1))
Y1_test = OHE.fit_transform(Y_test.reshape(-1,1))



In [0]:
from tensorflow.keras.utils import to_categorical
Y_train = to_categorical(Y_train,3)
Y_test = to_categorical(Y_test,3)

In [13]:
Y_train

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1

In [14]:
Y_test

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from tensorflow.keras import layers

model = tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
model.add(layers.Dense(4, activation='relu', input_shape=(4,)))
model.add(layers.Dense(3, activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [17]:
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

history = model.fit(X_train, Y_train,epochs=20, batch_size=1, verbose=1)

Train on 112 samples
Epoch 1/20
112/112 [==============================] - 1s 6ms/sample - loss: 0.9958 - accuracy: 0.5893
Epoch 2/20
112/112 [==============================] - 0s 1ms/sample - loss: 0.5688 - accuracy: 0.7143
Epoch 3/20
112/112 [==============================] - 0s 1ms/sample - loss: 0.4488 - accuracy: 0.7946
Epoch 4/20
112/112 [==============================] - 0s 1ms/sample - loss: 0.3952 - accuracy: 0.8393
Epoch 5/20
112/112 [==============================] - 0s 1ms/sample - loss: 0.3570 - accuracy: 0.8482
Epoch 6/20
112/112 [==============================] - 0s 1ms/sample - loss: 0.3456 - accuracy: 0.8036
Epoch 7/20
112/112 [==============================] - 0s 1ms/sample - loss: 0.3173 - accuracy: 0.8304
Epoch 8/20
112/112 [==============================] - 0s 1ms/sample - loss: 0.2628 - accuracy: 0.8929
Epoch 9/20
112/112 [==============================] - 0s 1ms/sample - loss: 0.2619 - accuracy: 0.9018
Epoch 10/20
112/112 [==============================] - 0s 1ms

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [19]:
history1 = model.fit(X_train, Y_train, validation_data=(X_test,Y_test) ,epochs=100, batch_size=1, verbose=1)

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1680 - accuracy: 0.9286 - val_loss: 0.2451 - val_accuracy: 0.8684
Epoch 2/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1711 - accuracy: 0.9464 - val_loss: 0.1581 - val_accuracy: 0.9474
Epoch 3/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1684 - accuracy: 0.9375 - val_loss: 0.1766 - val_accuracy: 0.9211
Epoch 4/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1581 - accuracy: 0.9375 - val_loss: 0.1490 - val_accuracy: 0.9474
Epoch 5/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1335 - accuracy: 0.9286 - val_loss: 0.2761 - val_accuracy: 0.8684
Epoch 6/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1612 - accuracy: 0.9196 - val_loss: 0.2572 - val_accuracy: 0.8684
Epoch 7/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1602 -

## Question 10

### Make predictions
- Predict labels on one row

In [20]:
y_pred = np.round(model.predict(X_test))
y_pred

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [21]:
model.predict(X_test[ 0:1 , : ])

array([[2.3995508e-08, 2.8742576e-02, 9.7125733e-01]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [22]:
Y_test[0:1 , : ]

array([[0., 0., 1.]], dtype=float32)

In [23]:
score = model.evaluate(X_test, Y_test,verbose=1)

print(score)

38/38 [==============================] - 0s 2ms/sample - loss: 0.1369 - accuracy: 0.9474
[0.1369056113456425, 0.94736844]




---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [25]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(47)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [29]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

Saving prices.csv to prices.csv


In [30]:
#prices=pd.read_csv('gdrive/My Drive/Colab Notebooks/prices.csv')
prices=pd.read_csv('prices.csv')
prices.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [31]:
df = prices.drop(['date', 'symbol'], axis = 1) 
df.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [32]:
df.shape

(851264, 5)

In [33]:
df.iloc[0:1000 , :]

open       close         low        high      volume
0    123.430000  125.839996  122.309998  126.250000   2163600.0
1    125.239998  119.980003  119.940002  125.540001   2386400.0
2    116.379997  114.949997  114.930000  119.739998   2489500.0
3    115.480003  116.620003  113.500000  117.440002   2006300.0
4    117.010002  114.970001  114.089996  117.330002   1408600.0
..          ...         ...         ...         ...         ...
995   63.310001   63.590000   63.240002   63.639999   2133200.0
996   27.160000   26.990000   26.680000   27.299999   1982400.0
997   28.320000   28.770000   28.010000   28.809999  37152800.0
998   44.000000   44.799999   43.750000   44.810001   6568600.0
999   36.080002   37.139999   36.009998   37.230000   5604300.0

[1000 rows x 5 columns]

In [34]:
prices_df = df.iloc[0:1000 , :]
prices_df.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
labels = prices_df['volume']
features = prices_df.drop('volume', axis=1)

In [0]:
labels = labels / 1000000

In [37]:
labels

0       2.1636
1       2.3864
2       2.4895
3       2.0063
4       1.4086
        ...   
995     2.1332
996     1.9824
997    37.1528
998     6.5686
999     5.6043
Name: volume, Length: 1000, dtype: float64

In [38]:
features

open       close         low        high
0    123.430000  125.839996  122.309998  126.250000
1    125.239998  119.980003  119.940002  125.540001
2    116.379997  114.949997  114.930000  119.739998
3    115.480003  116.620003  113.500000  117.440002
4    117.010002  114.970001  114.089996  117.330002
..          ...         ...         ...         ...
995   63.310001   63.590000   63.240002   63.639999
996   27.160000   26.990000   26.680000   27.299999
997   28.320000   28.770000   28.010000   28.809999
998   44.000000   44.799999   43.750000   44.810001
999   36.080002   37.139999   36.009998   37.230000

[1000 rows x 4 columns]

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [39]:
X = np.array(features).astype('float32')
Y= np.array(labels).astype('float32')
print(X.shape)
print(Y.shape)

(1000, 4)
(1000,)


In [40]:
X

array([[123.43, 125.84, 122.31, 126.25],
       [125.24, 119.98, 119.94, 125.54],
       [116.38, 114.95, 114.93, 119.74],
       ...,
       [ 28.32,  28.77,  28.01,  28.81],
       [ 44.  ,  44.8 ,  43.75,  44.81],
       [ 36.08,  37.14,  36.01,  37.23]], dtype=float32)

In [41]:
Y

array([2.163600e+00, 2.386400e+00, 2.489500e+00, 2.006300e+00,
       1.408600e+00, 1.098000e+00, 9.496000e-01, 7.853000e-01,
       1.093700e+00, 1.523500e+00, 1.653900e+00, 9.443000e-01,
       7.449000e-01, 7.038000e-01, 5.631000e-01, 8.961000e-01,
       6.804000e-01, 7.499000e-01, 5.742000e-01, 6.948000e-01,
       8.963000e-01, 9.563000e-01, 9.971000e-01, 1.200500e+00,
       1.725200e+00, 1.946000e+00, 1.319500e+00, 9.224000e-01,
       1.185100e+00, 9.215000e-01, 4.409000e-01, 1.244300e+00,
       6.813000e-01, 4.112000e-01, 4.473000e-01, 5.592000e-01,
       4.599000e-01, 9.716000e-01, 6.941000e-01, 1.159600e+00,
       8.847000e-01, 6.920000e-01, 8.980000e-01, 8.445000e-01,
       7.965000e-01, 4.168000e-01, 5.902000e-01, 4.951000e-01,
       5.158000e-01, 5.621000e-01, 8.093000e-01, 1.607300e+00,
       1.001300e+00, 7.114000e-01, 4.442000e-01, 5.341000e-01,
       7.982000e-01, 5.910000e-01, 4.432000e-01, 5.780000e-01,
       7.651000e-01, 5.143000e-01, 1.150000e+00, 2.0353

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
X=tf.math.l2_normalize(
    X,
    axis=None,
    epsilon=1e-12,
    name=None
)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
W = tf.zeros(shape=(4, 1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function
def prediction(features, W, b):
    y_pred = tf.add(tf.matmul(features, W), b)
    return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function
def loss(y_actual, y_predicted):
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    # Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        t.watch([w,b])
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    # Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    # Update Weights and Bias
    w = w - learning_rate * dw
    b = b - learning_rate * db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [47]:
for i in range(100):    
    W, b = train(X, Y, W, b)
    print('Current Training Loss on iteration', i, loss(Y, prediction(X, W, b)))

Current Training Loss on iteration 0 tf.Tensor(236.16759, shape=(), dtype=float32)
Current Training Loss on iteration 1 tf.Tensor(235.09299, shape=(), dtype=float32)
Current Training Loss on iteration 2 tf.Tensor(234.06102, shape=(), dtype=float32)
Current Training Loss on iteration 3 tf.Tensor(233.06998, shape=(), dtype=float32)
Current Training Loss on iteration 4 tf.Tensor(232.11781, shape=(), dtype=float32)
Current Training Loss on iteration 5 tf.Tensor(231.20381, shape=(), dtype=float32)
Current Training Loss on iteration 6 tf.Tensor(230.32585, shape=(), dtype=float32)
Current Training Loss on iteration 7 tf.Tensor(229.48265, shape=(), dtype=float32)
Current Training Loss on iteration 8 tf.Tensor(228.67297, shape=(), dtype=float32)
Current Training Loss on iteration 9 tf.Tensor(227.89539, shape=(), dtype=float32)
Current Training Loss on iteration 10 tf.Tensor(227.14832, shape=(), dtype=float32)
Current Training Loss on iteration 11 tf.Tensor(226.43114, shape=(), dtype=float32)
Cu

### Observe values of Weight
- Print the updated values

In [48]:
print(W)

tf.Tensor(
[[0.0547828 ]
 [0.05488191]
 [0.05422735]
 [0.05533117]], shape=(4, 1), dtype=float32)


### Observe values of Bias
- Print the updated values

In [49]:
print(b)

tf.Tensor([4.607657], shape=(1,), dtype=float32)
